In [1]:
import torch

In [2]:
x = torch.ones(2,2,requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [3]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [4]:
z = y * y * 3
out = z.mean()

In [5]:
print(z)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)


In [6]:
print(out)

tensor(27., grad_fn=<MeanBackward0>)


In [7]:
out.backward()

In [8]:
dodx = x.grad

In [9]:
print(dodx)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [10]:
x1 = torch.ones(10,1,requires_grad=True)
x1

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]], requires_grad=True)

In [11]:
y1 = torch.ones(10,2,requires_grad=True)
y1

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], requires_grad=True)

In [12]:
a = torch.ones(1,2)
a[0][0] = 2
a[0][1] = 3
a

tensor([[2., 3.]])

In [13]:
y1 = x1*a
y1

tensor([[2., 3.],
        [2., 3.],
        [2., 3.],
        [2., 3.],
        [2., 3.],
        [2., 3.],
        [2., 3.],
        [2., 3.],
        [2., 3.],
        [2., 3.]], grad_fn=<MulBackward0>)

In [14]:
b = torch.ones(1,2)
b[0][0] = -1
b[0][1] = 1
b

tensor([[-1.,  1.]])

In [15]:
z = y1 + b
z

tensor([[1., 4.],
        [1., 4.],
        [1., 4.],
        [1., 4.],
        [1., 4.],
        [1., 4.],
        [1., 4.],
        [1., 4.],
        [1., 4.],
        [1., 4.]], grad_fn=<AddBackward0>)

In [16]:
z[:,0].backward(torch.ones_like(z[:,0]), retain_graph=True)

In [17]:
x1.grad

tensor([[2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.]])

In [18]:
if x1.grad is not None:
    x1.grad.data.zero_()

In [19]:
z[:,1].backward(torch.ones_like(z[:,1]))

In [20]:
x1.grad

tensor([[3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.]])